### ISSUE TITLE
doesn't appear to be working

### ISSUE THREAD

**Issue by spyhunter99** [jchrispen/bjs-clip-it#3]
not sure what the issue is. says clipping coupons in the console but it's not doing anything

**Comment by MacGurus** [comment]
i can confirm 'she's dead jim'                                                                                 does not appear to be doing anything presently

**Comment by MacGurus** [comment]
tried activating after already being logged in - tried fresh browser session clicked plugin which did take me to the bjs site as per instructions - logged in and it doesn't seem to do anything - can't think of any other way to possibly jump start the clicking process

**Comment by jchrispen** [comment]
Confirmed, it stopped working. I'll take a look at it and see if I can get it working again. They probably changed the coupon API.

**Comment by jchrispen** [comment]
Okay, I think I have it patched up and added support for a 2nd site. Check out the new release! 
[Clip-It!](https://addons.mozilla.org/en-US/firefox/addon/bjs-clip-it/)

**Comment by MacGurus** [comment]
working great thanks - ublock origin seemed to be interfering with it but once disabled it grabbed all the coupons
